/* Comms.java is generated by gen_comms.py from CommsTemplate.java. 
DO NOT MODIFY THIS FILE DIRECTLY */
package US_QUAL;

import battlecode.common.*;

public class Comms extends RobotPlayer {
    private static int buf0,buf1,buf2,buf3,buf4,buf5,buf6,buf7,buf8,buf9,buf10,buf11,buf12,buf13,buf14,buf15,buf16,buf17,buf18,buf19,buf20,buf21,buf22,buf23,buf24,buf25,buf26,buf27,buf28,buf29,buf30,buf31,buf32,buf33,buf34,buf35,buf36,buf37,buf38,buf39,buf40,buf41,buf42,buf43,buf44,buf45,buf46,buf47,buf48,buf49,buf50,buf51,buf52,buf53,buf54,buf55,buf56,buf57,buf58,buf59,buf60,buf61,buf62,buf63;
    private static int dirty0,dirty1,dirty2,dirty3,dirty4,dirty5,dirty6,dirty7,dirty8,dirty9,dirty10,dirty11,dirty12,dirty13,dirty14,dirty15,dirty16,dirty17,dirty18,dirty19,dirty20,dirty21,dirty22,dirty23,dirty24,dirty25,dirty26,dirty27,dirty28,dirty29,dirty30,dirty31,dirty32,dirty33,dirty34,dirty35,dirty36,dirty37,dirty38,dirty39,dirty40,dirty41,dirty42,dirty43,dirty44,dirty45,dirty46,dirty47,dirty48,dirty49,dirty50,dirty51,dirty52,dirty53,dirty54,dirty55,dirty56,dirty57,dirty58,dirty59,dirty60,dirty61,dirty62,dirty63;

    public final static int SYNC_SLOTS = 1;
    public final static int HQ_SLOTS = 3;
    public final static int SYMMETRY_SLOTS = 1;
    public final static int MYFLAGS_SLOTS = 3;
    public final static int OPPFLAGS_SLOTS = 3;
    public final static int MYTEAM_SLOTS = 1;
    public final static int OPPTEAM_SLOTS = 1;
    public final static int ENEMY_SLOTS = 3;

    public static void pull() throws GameActionException {
        buf0 = rc.readSharedArray(0);
        buf1 = rc.readSharedArray(1);
        buf2 = rc.readSharedArray(2);
        buf3 = rc.readSharedArray(3);
        buf4 = rc.readSharedArray(4);
        buf5 = rc.readSharedArray(5);
        buf6 = rc.readSharedArray(6);
        buf7 = rc.readSharedArray(7);
        buf8 = rc.readSharedArray(8);
        buf9 = rc.readSharedArray(9);
        buf10 = rc.readSharedArray(10);
        buf11 = rc.readSharedArray(11);
        buf12 = rc.readSharedArray(12);
        buf13 = rc.readSharedArray(13);
        buf14 = rc.readSharedArray(14);
        buf15 = rc.readSharedArray(15);
        buf16 = rc.readSharedArray(16);
        buf17 = rc.readSharedArray(17);
        buf18 = rc.readSharedArray(18);
        buf19 = rc.readSharedArray(19);
        buf20 = rc.readSharedArray(20);
        buf21 = rc.readSharedArray(21);
        buf22 = rc.readSharedArray(22);
        buf23 = rc.readSharedArray(23);
        buf24 = rc.readSharedArray(24);
        buf25 = rc.readSharedArray(25);
        buf26 = rc.readSharedArray(26);
        buf27 = rc.readSharedArray(27);
        buf28 = rc.readSharedArray(28);
        buf29 = rc.readSharedArray(29);
        buf30 = rc.readSharedArray(30);
        buf31 = rc.readSharedArray(31);
        buf32 = rc.readSharedArray(32);
        buf33 = rc.readSharedArray(33);
        buf34 = rc.readSharedArray(34);
        buf35 = rc.readSharedArray(35);
        buf36 = rc.readSharedArray(36);
        buf37 = rc.readSharedArray(37);
        buf38 = rc.readSharedArray(38);
        buf39 = rc.readSharedArray(39);
        buf40 = rc.readSharedArray(40);
        buf41 = rc.readSharedArray(41);
        buf42 = rc.readSharedArray(42);
        buf43 = rc.readSharedArray(43);
        buf44 = rc.readSharedArray(44);
        buf45 = rc.readSharedArray(45);
        buf46 = rc.readSharedArray(46);
        buf47 = rc.readSharedArray(47);
        buf48 = rc.readSharedArray(48);
        buf49 = rc.readSharedArray(49);
        buf50 = rc.readSharedArray(50);
        buf51 = rc.readSharedArray(51);
        buf52 = rc.readSharedArray(52);
        buf53 = rc.readSharedArray(53);
        buf54 = rc.readSharedArray(54);
        buf55 = rc.readSharedArray(55);
        buf56 = rc.readSharedArray(56);
        buf57 = rc.readSharedArray(57);
        buf58 = rc.readSharedArray(58);
        buf59 = rc.readSharedArray(59);
        buf60 = rc.readSharedArray(60);
        buf61 = rc.readSharedArray(61);
        buf62 = rc.readSharedArray(62);
        buf63 = rc.readSharedArray(63);
    }

    public static void push() throws GameActionException {
        switch (dirty0) {case 1: rc.writeSharedArray(0, buf0); dirty0 = 0;}
        switch (dirty1) {case 1: rc.writeSharedArray(1, buf1); dirty1 = 0;}
        switch (dirty2) {case 1: rc.writeSharedArray(2, buf2); dirty2 = 0;}
        switch (dirty3) {case 1: rc.writeSharedArray(3, buf3); dirty3 = 0;}
        switch (dirty4) {case 1: rc.writeSharedArray(4, buf4); dirty4 = 0;}
        switch (dirty5) {case 1: rc.writeSharedArray(5, buf5); dirty5 = 0;}
        switch (dirty6) {case 1: rc.writeSharedArray(6, buf6); dirty6 = 0;}
        switch (dirty7) {case 1: rc.writeSharedArray(7, buf7); dirty7 = 0;}
        switch (dirty8) {case 1: rc.writeSharedArray(8, buf8); dirty8 = 0;}
        switch (dirty9) {case 1: rc.writeSharedArray(9, buf9); dirty9 = 0;}
        switch (dirty10) {case 1: rc.writeSharedArray(10, buf10); dirty10 = 0;}
        switch (dirty11) {case 1: rc.writeSharedArray(11, buf11); dirty11 = 0;}
        switch (dirty12) {case 1: rc.writeSharedArray(12, buf12); dirty12 = 0;}
        switch (dirty13) {case 1: rc.writeSharedArray(13, buf13); dirty13 = 0;}
        switch (dirty14) {case 1: rc.writeSharedArray(14, buf14); dirty14 = 0;}
        switch (dirty15) {case 1: rc.writeSharedArray(15, buf15); dirty15 = 0;}
        switch (dirty16) {case 1: rc.writeSharedArray(16, buf16); dirty16 = 0;}
        switch (dirty17) {case 1: rc.writeSharedArray(17, buf17); dirty17 = 0;}
        switch (dirty18) {case 1: rc.writeSharedArray(18, buf18); dirty18 = 0;}
        switch (dirty19) {case 1: rc.writeSharedArray(19, buf19); dirty19 = 0;}
        switch (dirty20) {case 1: rc.writeSharedArray(20, buf20); dirty20 = 0;}
        switch (dirty21) {case 1: rc.writeSharedArray(21, buf21); dirty21 = 0;}
        switch (dirty22) {case 1: rc.writeSharedArray(22, buf22); dirty22 = 0;}
        switch (dirty23) {case 1: rc.writeSharedArray(23, buf23); dirty23 = 0;}
        switch (dirty24) {case 1: rc.writeSharedArray(24, buf24); dirty24 = 0;}
        switch (dirty25) {case 1: rc.writeSharedArray(25, buf25); dirty25 = 0;}
        switch (dirty26) {case 1: rc.writeSharedArray(26, buf26); dirty26 = 0;}
        switch (dirty27) {case 1: rc.writeSharedArray(27, buf27); dirty27 = 0;}
        switch (dirty28) {case 1: rc.writeSharedArray(28, buf28); dirty28 = 0;}
        switch (dirty29) {case 1: rc.writeSharedArray(29, buf29); dirty29 = 0;}
        switch (dirty30) {case 1: rc.writeSharedArray(30, buf30); dirty30 = 0;}
        switch (dirty31) {case 1: rc.writeSharedArray(31, buf31); dirty31 = 0;}
        switch (dirty32) {case 1: rc.writeSharedArray(32, buf32); dirty32 = 0;}
        switch (dirty33) {case 1: rc.writeSharedArray(33, buf33); dirty33 = 0;}
        switch (dirty34) {case 1: rc.writeSharedArray(34, buf34); dirty34 = 0;}
        switch (dirty35) {case 1: rc.writeSharedArray(35, buf35); dirty35 = 0;}
        switch (dirty36) {case 1: rc.writeSharedArray(36, buf36); dirty36 = 0;}
        switch (dirty37) {case 1: rc.writeSharedArray(37, buf37); dirty37 = 0;}
        switch (dirty38) {case 1: rc.writeSharedArray(38, buf38); dirty38 = 0;}
        switch (dirty39) {case 1: rc.writeSharedArray(39, buf39); dirty39 = 0;}
        switch (dirty40) {case 1: rc.writeSharedArray(40, buf40); dirty40 = 0;}
        switch (dirty41) {case 1: rc.writeSharedArray(41, buf41); dirty41 = 0;}
        switch (dirty42) {case 1: rc.writeSharedArray(42, buf42); dirty42 = 0;}
        switch (dirty43) {case 1: rc.writeSharedArray(43, buf43); dirty43 = 0;}
        switch (dirty44) {case 1: rc.writeSharedArray(44, buf44); dirty44 = 0;}
        switch (dirty45) {case 1: rc.writeSharedArray(45, buf45); dirty45 = 0;}
        switch (dirty46) {case 1: rc.writeSharedArray(46, buf46); dirty46 = 0;}
        switch (dirty47) {case 1: rc.writeSharedArray(47, buf47); dirty47 = 0;}
        switch (dirty48) {case 1: rc.writeSharedArray(48, buf48); dirty48 = 0;}
        switch (dirty49) {case 1: rc.writeSharedArray(49, buf49); dirty49 = 0;}
        switch (dirty50) {case 1: rc.writeSharedArray(50, buf50); dirty50 = 0;}
        switch (dirty51) {case 1: rc.writeSharedArray(51, buf51); dirty51 = 0;}
        switch (dirty52) {case 1: rc.writeSharedArray(52, buf52); dirty52 = 0;}
        switch (dirty53) {case 1: rc.writeSharedArray(53, buf53); dirty53 = 0;}
        switch (dirty54) {case 1: rc.writeSharedArray(54, buf54); dirty54 = 0;}
        switch (dirty55) {case 1: rc.writeSharedArray(55, buf55); dirty55 = 0;}
        switch (dirty56) {case 1: rc.writeSharedArray(56, buf56); dirty56 = 0;}
        switch (dirty57) {case 1: rc.writeSharedArray(57, buf57); dirty57 = 0;}
        switch (dirty58) {case 1: rc.writeSharedArray(58, buf58); dirty58 = 0;}
        switch (dirty59) {case 1: rc.writeSharedArray(59, buf59); dirty59 = 0;}
        switch (dirty60) {case 1: rc.writeSharedArray(60, buf60); dirty60 = 0;}
        switch (dirty61) {case 1: rc.writeSharedArray(61, buf61); dirty61 = 0;}
        switch (dirty62) {case 1: rc.writeSharedArray(62, buf62); dirty62 = 0;}
        switch (dirty63) {case 1: rc.writeSharedArray(63, buf63); dirty63 = 0;}
    }


    public static int readSyncId() throws GameActionException {
        return (buf0 & 65528) >>> 3;
    }

    public static void writeSyncId(int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 8192, "write value out of range");
        buf0 = (buf0 & 7) | (value << 3);
        dirty0 = 1;
    }

    public static int readHqLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf0 & 7) << 9) + ((buf1 & 65408) >>> 7);
            case 1: return ((buf2 & 1023) << 2) + ((buf3 & 49152) >>> 14);
            case 2: return ((buf3 & 1) << 11) + ((buf4 & 65504) >>> 5);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeHqLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf0 = (buf0 & 65528) | ((value & 3584) >>> 9);
                dirty0 = 1;
                buf1 = (buf1 & 127) | ((value & 511) << 7);
                dirty1 = 1;
                break;
            case 1:
                buf2 = (buf2 & 64512) | ((value & 4092) >>> 2);
                dirty2 = 1;
                buf3 = (buf3 & 16383) | ((value & 3) << 14);
                dirty3 = 1;
                break;
            case 2:
                buf3 = (buf3 & 65534) | ((value & 2048) >>> 11);
                dirty3 = 1;
                buf4 = (buf4 & 31) | ((value & 2047) << 5);
                dirty4 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readHqDis2next(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf1 & 127) << 1) + ((buf2 & 32768) >>> 15);
            case 1: return (buf3 & 16320) >>> 6;
            case 2: return ((buf4 & 31) << 3) + ((buf5 & 57344) >>> 13);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeHqDis2next(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 256, "write value out of range");
        switch (idx) {
            case 0:
                buf1 = (buf1 & 65408) | ((value & 254) >>> 1);
                dirty1 = 1;
                buf2 = (buf2 & 32767) | ((value & 1) << 15);
                dirty2 = 1;
                break;
            case 1:
                buf3 = (buf3 & 49215) | (value << 6);
                dirty3 = 1;
                break;
            case 2:
                buf4 = (buf4 & 65504) | ((value & 248) >>> 3);
                dirty4 = 1;
                buf5 = (buf5 & 8191) | ((value & 7) << 13);
                dirty5 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readHqCongestround(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf2 & 31744) >>> 10;
            case 1: return (buf3 & 62) >>> 1;
            case 2: return (buf5 & 7936) >>> 8;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeHqCongestround(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 32, "write value out of range");
        switch (idx) {
            case 0:
                buf2 = (buf2 & 33791) | (value << 10);
                dirty2 = 1;
                break;
            case 1:
                buf3 = (buf3 & 65473) | (value << 1);
                dirty3 = 1;
                break;
            case 2:
                buf5 = (buf5 & 57599) | (value << 8);
                dirty5 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readSymmetrySym() throws GameActionException {
        return (buf5 & 224) >>> 5;
    }

    public static void writeSymmetrySym(int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 8, "write value out of range");
        buf5 = (buf5 & 65311) | (value << 5);
        dirty5 = 1;
    }

    public static int readMyflagsId(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf5 & 31) << 7) + ((buf6 & 65024) >>> 9);
            case 1: return ((buf8 & 3) << 10) + ((buf9 & 65472) >>> 6);
            case 2: return (buf12 & 32760) >>> 3;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsId(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf5 = (buf5 & 65504) | ((value & 3968) >>> 7);
                dirty5 = 1;
                buf6 = (buf6 & 511) | ((value & 127) << 9);
                dirty6 = 1;
                break;
            case 1:
                buf8 = (buf8 & 65532) | ((value & 3072) >>> 10);
                dirty8 = 1;
                buf9 = (buf9 & 63) | ((value & 1023) << 6);
                dirty9 = 1;
                break;
            case 2:
                buf12 = (buf12 & 32775) | (value << 3);
                dirty12 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyflagsExists(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf6 & 256) >>> 8;
            case 1: return (buf9 & 32) >>> 5;
            case 2: return (buf12 & 4) >>> 2;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsExists(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 2, "write value out of range");
        switch (idx) {
            case 0:
                buf6 = (buf6 & 65279) | (value << 8);
                dirty6 = 1;
                break;
            case 1:
                buf9 = (buf9 & 65503) | (value << 5);
                dirty9 = 1;
                break;
            case 2:
                buf12 = (buf12 & 65531) | (value << 2);
                dirty12 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyflagsLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf6 & 255) << 4) + ((buf7 & 61440) >>> 12);
            case 1: return ((buf9 & 31) << 7) + ((buf10 & 65024) >>> 9);
            case 2: return ((buf12 & 3) << 10) + ((buf13 & 65472) >>> 6);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf6 = (buf6 & 65280) | ((value & 4080) >>> 4);
                dirty6 = 1;
                buf7 = (buf7 & 4095) | ((value & 15) << 12);
                dirty7 = 1;
                break;
            case 1:
                buf9 = (buf9 & 65504) | ((value & 3968) >>> 7);
                dirty9 = 1;
                buf10 = (buf10 & 511) | ((value & 127) << 9);
                dirty10 = 1;
                break;
            case 2:
                buf12 = (buf12 & 65532) | ((value & 3072) >>> 10);
                dirty12 = 1;
                buf13 = (buf13 & 63) | ((value & 1023) << 6);
                dirty13 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyflagsOriginalLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf7 & 4095);
            case 1: return ((buf10 & 511) << 3) + ((buf11 & 57344) >>> 13);
            case 2: return ((buf13 & 63) << 6) + ((buf14 & 64512) >>> 10);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsOriginalLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf7 = (buf7 & 61440) | (value);
                dirty7 = 1;
                break;
            case 1:
                buf10 = (buf10 & 65024) | ((value & 4088) >>> 3);
                dirty10 = 1;
                buf11 = (buf11 & 8191) | ((value & 7) << 13);
                dirty11 = 1;
                break;
            case 2:
                buf13 = (buf13 & 65472) | ((value & 4032) >>> 6);
                dirty13 = 1;
                buf14 = (buf14 & 1023) | ((value & 63) << 10);
                dirty14 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyflagsAssigned(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf8 & 64512) >>> 10;
            case 1: return (buf11 & 8064) >>> 7;
            case 2: return (buf14 & 1008) >>> 4;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsAssigned(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 64, "write value out of range");
        switch (idx) {
            case 0:
                buf8 = (buf8 & 1023) | (value << 10);
                dirty8 = 1;
                break;
            case 1:
                buf11 = (buf11 & 57471) | (value << 7);
                dirty11 = 1;
                break;
            case 2:
                buf14 = (buf14 & 64527) | (value << 4);
                dirty14 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyflagsDistress(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf8 & 512) >>> 9;
            case 1: return (buf11 & 64) >>> 6;
            case 2: return (buf14 & 8) >>> 3;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsDistress(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 2, "write value out of range");
        switch (idx) {
            case 0:
                buf8 = (buf8 & 65023) | (value << 9);
                dirty8 = 1;
                break;
            case 1:
                buf11 = (buf11 & 65471) | (value << 6);
                dirty11 = 1;
                break;
            case 2:
                buf14 = (buf14 & 65527) | (value << 3);
                dirty14 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyflagsNotSeenCnt(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf8 & 508) >>> 2;
            case 1: return ((buf11 & 63) << 1) + ((buf12 & 32768) >>> 15);
            case 2: return ((buf14 & 7) << 4) + ((buf15 & 61440) >>> 12);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeMyflagsNotSeenCnt(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 128, "write value out of range");
        switch (idx) {
            case 0:
                buf8 = (buf8 & 65027) | (value << 2);
                dirty8 = 1;
                break;
            case 1:
                buf11 = (buf11 & 65472) | ((value & 126) >>> 1);
                dirty11 = 1;
                buf12 = (buf12 & 32767) | ((value & 1) << 15);
                dirty12 = 1;
                break;
            case 2:
                buf14 = (buf14 & 65528) | ((value & 112) >>> 4);
                dirty14 = 1;
                buf15 = (buf15 & 4095) | ((value & 15) << 12);
                dirty15 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsId(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf15 & 4095);
            case 1: return ((buf18 & 7) << 9) + ((buf19 & 65408) >>> 7);
            case 2: return ((buf22 & 1023) << 2) + ((buf23 & 49152) >>> 14);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsId(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf15 = (buf15 & 61440) | (value);
                dirty15 = 1;
                break;
            case 1:
                buf18 = (buf18 & 65528) | ((value & 3584) >>> 9);
                dirty18 = 1;
                buf19 = (buf19 & 127) | ((value & 511) << 7);
                dirty19 = 1;
                break;
            case 2:
                buf22 = (buf22 & 64512) | ((value & 4092) >>> 2);
                dirty22 = 1;
                buf23 = (buf23 & 16383) | ((value & 3) << 14);
                dirty23 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsExists(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf16 & 32768) >>> 15;
            case 1: return (buf19 & 64) >>> 6;
            case 2: return (buf23 & 8192) >>> 13;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsExists(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 2, "write value out of range");
        switch (idx) {
            case 0:
                buf16 = (buf16 & 32767) | (value << 15);
                dirty16 = 1;
                break;
            case 1:
                buf19 = (buf19 & 65471) | (value << 6);
                dirty19 = 1;
                break;
            case 2:
                buf23 = (buf23 & 57343) | (value << 13);
                dirty23 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf16 & 32760) >>> 3;
            case 1: return ((buf19 & 63) << 6) + ((buf20 & 64512) >>> 10);
            case 2: return (buf23 & 8190) >>> 1;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf16 = (buf16 & 32775) | (value << 3);
                dirty16 = 1;
                break;
            case 1:
                buf19 = (buf19 & 65472) | ((value & 4032) >>> 6);
                dirty19 = 1;
                buf20 = (buf20 & 1023) | ((value & 63) << 10);
                dirty20 = 1;
                break;
            case 2:
                buf23 = (buf23 & 57345) | (value << 1);
                dirty23 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsOriginalLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf16 & 7) << 9) + ((buf17 & 65408) >>> 7);
            case 1: return ((buf20 & 1023) << 2) + ((buf21 & 49152) >>> 14);
            case 2: return ((buf23 & 1) << 11) + ((buf24 & 65504) >>> 5);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsOriginalLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf16 = (buf16 & 65528) | ((value & 3584) >>> 9);
                dirty16 = 1;
                buf17 = (buf17 & 127) | ((value & 511) << 7);
                dirty17 = 1;
                break;
            case 1:
                buf20 = (buf20 & 64512) | ((value & 4092) >>> 2);
                dirty20 = 1;
                buf21 = (buf21 & 16383) | ((value & 3) << 14);
                dirty21 = 1;
                break;
            case 2:
                buf23 = (buf23 & 65534) | ((value & 2048) >>> 11);
                dirty23 = 1;
                buf24 = (buf24 & 31) | ((value & 2047) << 5);
                dirty24 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsEscortLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf17 & 127) << 5) + ((buf18 & 63488) >>> 11);
            case 1: return (buf21 & 16380) >>> 2;
            case 2: return ((buf24 & 31) << 7) + ((buf25 & 65024) >>> 9);
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsEscortLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf17 = (buf17 & 65408) | ((value & 4064) >>> 5);
                dirty17 = 1;
                buf18 = (buf18 & 2047) | ((value & 31) << 11);
                dirty18 = 1;
                break;
            case 1:
                buf21 = (buf21 & 49155) | (value << 2);
                dirty21 = 1;
                break;
            case 2:
                buf24 = (buf24 & 65504) | ((value & 3968) >>> 7);
                dirty24 = 1;
                buf25 = (buf25 & 511) | ((value & 127) << 9);
                dirty25 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsConfirmed(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf18 & 1024) >>> 10;
            case 1: return (buf21 & 2) >>> 1;
            case 2: return (buf25 & 256) >>> 8;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsConfirmed(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 2, "write value out of range");
        switch (idx) {
            case 0:
                buf18 = (buf18 & 64511) | (value << 10);
                dirty18 = 1;
                break;
            case 1:
                buf21 = (buf21 & 65533) | (value << 1);
                dirty21 = 1;
                break;
            case 2:
                buf25 = (buf25 & 65279) | (value << 8);
                dirty25 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsCarried(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf18 & 512) >>> 9;
            case 1: return (buf21 & 1);
            case 2: return (buf25 & 128) >>> 7;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsCarried(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 2, "write value out of range");
        switch (idx) {
            case 0:
                buf18 = (buf18 & 65023) | (value << 9);
                dirty18 = 1;
                break;
            case 1:
                buf21 = (buf21 & 65534) | (value);
                dirty21 = 1;
                break;
            case 2:
                buf25 = (buf25 & 65407) | (value << 7);
                dirty25 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readOppflagsAssigned(int idx) throws GameActionException {
        switch (idx) {
            case 0: return (buf18 & 504) >>> 3;
            case 1: return (buf22 & 64512) >>> 10;
            case 2: return (buf25 & 126) >>> 1;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeOppflagsAssigned(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 64, "write value out of range");
        switch (idx) {
            case 0:
                buf18 = (buf18 & 65031) | (value << 3);
                dirty18 = 1;
                break;
            case 1:
                buf22 = (buf22 & 1023) | (value << 10);
                dirty22 = 1;
                break;
            case 2:
                buf25 = (buf25 & 65409) | (value << 1);
                dirty25 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    public static int readMyteamCnt() throws GameActionException {
        return ((buf25 & 1) << 5) + ((buf26 & 63488) >>> 11);
    }

    public static void writeMyteamCnt(int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 64, "write value out of range");
        buf25 = (buf25 & 65534) | ((value & 32) >>> 5);
        dirty25 = 1;
        buf26 = (buf26 & 2047) | ((value & 31) << 11);
        dirty26 = 1;
    }

    public static int readOppteamCnt() throws GameActionException {
        return (buf26 & 2016) >>> 5;
    }

    public static void writeOppteamCnt(int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 64, "write value out of range");
        buf26 = (buf26 & 63519) | (value << 5);
        dirty26 = 1;
    }

    public static int readEnemyLoc(int idx) throws GameActionException {
        switch (idx) {
            case 0: return ((buf26 & 31) << 7) + ((buf27 & 65024) >>> 9);
            case 1: return ((buf27 & 511) << 3) + ((buf28 & 57344) >>> 13);
            case 2: return (buf28 & 8190) >>> 1;
            default:
                Debug.failFast("Comm read param not in range"); return -1;
        }
    }

    public static void writeEnemyLoc(int idx, int value) throws GameActionException {Debug.betterAssert(value >= 0 && value < 4096, "write value out of range");
        switch (idx) {
            case 0:
                buf26 = (buf26 & 65504) | ((value & 3968) >>> 7);
                dirty26 = 1;
                buf27 = (buf27 & 511) | ((value & 127) << 9);
                dirty27 = 1;
                break;
            case 1:
                buf27 = (buf27 & 65024) | ((value & 4088) >>> 3);
                dirty27 = 1;
                buf28 = (buf28 & 8191) | ((value & 7) << 13);
                dirty28 = 1;
                break;
            case 2:
                buf28 = (buf28 & 57345) | (value << 1);
                dirty28 = 1;
                break;
            default:
                Debug.failFast("Comm write param not in range"); 
        }
    }

    // BUFFER POOL READ AND WRITE METHODS

}